RET-1842: ET1 Vetting - Jurisdiction codes
hmcts/et-ccd-definitions-englandwales pull request #137
Opened 2022-06-25 11:14 UTC by robin-ieong

(https://tools.hmcts.net/jira/browse/RET-1842
https://tools.hmcts.net/jira/browse/RET-1843)

### Change description ###
This PR contains the implementation of both RET-1842 and RET-1843, please see tickets.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-06-26 09:32 UTC, nickwest1 approved these changes

2022-06-27 15:20 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "UserRole": "caseworker-employment-etjudge",
Change UseRole access for caseworker-employment-etjudge and caseworker-employment to R for all fields.

2022-06-27 15:21 UTC, Itay-Kirsh requested changes
Change UseRole access for caseworker-employment-etjudge and caseworker-employment to R for all fields.

2022-06-30 11:44 UTC, Itay-Kirsh requested changes

2022-06-30 11:44 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "CaseFieldID": "existingJurisdictionCodes",
This is a readonly user role.

2022-06-30 11:44 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "CaseFieldID": "existingJurisdictionCodes",
There's many other examples, I only pointed out one.

2022-06-30 13:25 UTC, Itay-Kirsh approved these changes

2022-06-30 13:28 UTC, merged