Ret 2058
hmcts/et-ccd-definitions-englandwales pull request #200
Opened 2022-07-15 11:38 UTC by robin-ieong

(https://tools.hmcts.net/jira/browse/RET-2058)

### Change description ###
A Respondent has submitted an ET3 Form which has been vetted and accepted by case workers. Now all parties need to be told the form has been received and accepted, and a copy of the ET3 form must be sent to the Claimant.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2022-07-15 13:08 UTC, jsinghm13 commented on definitions/json/CaseEventToFields.json
> +    "PageLabel": "Send documents",
I don't think you need to set this value again when it has been already set in the first field on the page

2022-07-15 14:11 UTC, jsinghm13 approved these changes

2022-07-15 14:16 UTC, Itay-Kirsh requested changes

2022-07-15 14:16 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "UserRole": "caseworker-employment",
R only role

2022-07-15 14:16 UTC, Itay-Kirsh commented on definitions/json/AuthorisationCaseField.json
> +    "UserRole": "caseworker-employment-etjudge",
R only role

2022-07-15 14:39 UTC, hsjhita commented on definitions/json/AuthorisationCaseField.json
> +    "CRUD": "CRUD"
R

2022-07-15 14:40 UTC, hsjhita commented on definitions/json/CaseEventToFields.json
> -    "PageLabel": "Send documents",
Intentional?

2022-07-15 14:41 UTC, hsjhita commented on definitions/json/CaseEventToFields.json
> +    "DisplayContext": "MANDATORY",
This should be COMPLEX - the fields part of the complexType should then be listed on EventToComplexTypes

2022-07-15 16:20 UTC, jsinghm13 submitted a review, later dismissed

2022-07-19 14:23 UTC, Itay-Kirsh approved these changes

2022-07-19 15:39 UTC, jsinghm13 approved these changes

2022-07-19 15:39 UTC, merged