Ret 2183
hmcts/et-ccd-definitions-englandwales pull request #224
Opened 2022-08-05 10:16 UTC by robin-ieong

(https://tools.hmcts.net/jira/browse/RET-2183)
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-08-05 15:24 UTC, Brogie commented on definitions/json/CaseField.json
> +    "Label": "<a href=\"/cases/case-details/${[CASE_REFERENCE]}/trigger/createReferral/createReferral1\">Send a new referral</a> <br> <a href=\"/cases/case-details/${[CASE_REFERENCE]}#Documents\" tar
test this in demo apparently there is issues with this method of linking

2022-08-05 15:26 UTC, Brogie approved these changes

2022-08-19 07:50 UTC, hsjhita commented on definitions/json/CaseEventToFields.json
> +    "FieldShowCondition": "et1JurisdictionCodeGeneralNotes=\"dummy\"",
Not the best of fieldShow conditions - what if someone actually typed in dummy on the general notes box? This field would then show

2022-08-19 07:51 UTC, hsjhita commented on definitions/json/CaseField.json
> +    "Label": "<a href=\"/cases/case-details/${[CASE_REFERENCE]}/trigger/createReferral/createReferral1\">Send a new referral</a> <br> <a href=\"/cases/case-details/${[CASE_REFERENCE]}/trigger/replyTo
FieldType on new line

2022-08-19 07:54 UTC, hsjhita commented on definitions/json/CaseTypeTab.json
> +    "TabID": "CaseDocuments",
History should be tab 15, Document should be tab 16. This was a change made to resolve an ExUI bug

2022-08-22 15:56 UTC, JackReevies approved these changes

2022-08-22 16:05 UTC, JackReevies commented on definitions/json/CaseEventToFields.json
> +    "PageFieldDisplayOrder": 1,
Should this be 11?

2022-08-22 16:05 UTC, JackReevies commented on definitions/json/CaseField.json
> +    "FieldTypeParameter": "fl_ReferCaseTo",
frl_ReferCaseTo? since its a Fixed Radio List not a Fixed List

2022-08-22 16:06 UTC, JackReevies requested changes
see comments

2022-08-23 07:45 UTC, hsjhita commented on definitions/json/CaseEventToFields.json
> +    "FieldShowCondition": "et1SubstantiveDefectsGeneralNotes=\"dummy dummy dummy dum dummy\"",
What I meant with my previous comment on this was not to set a text field as the show condition. The user can still type in dummy dummy dummy dum dummy and this field would appear. Maybe set the field for the condition as a YesNo field.

2022-08-23 07:45 UTC, hsjhita commented on definitions/json/CaseEventToFields.json
> +    "PageFieldDisplayOrder": 1,
Different CaseEventID

2022-08-23 09:18 UTC, hsjhita approved these changes

2022-08-23 09:20 UTC, merged