RET-3857: Add private hearing question as part of initial consideration
hmcts/et-ccd-definitions-englandwales pull request #580
Opened 2023-07-17 10:52 UTC by jip1984

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-3857

### Change description ###
Add private hearing question as part of initial consideration, made changes to CaseFields.json, CaseEventToField.json and AuthorisationCaseField.json

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-17 12:52 UTC, robin-ieong approved these changes

2023-07-18 08:50 UTC, JackReevies requested changes

2023-07-18 08:50 UTC, JackReevies commented on definitions/json/AuthorisationCaseField.json
> +},
Can we align this plz

2023-07-18 08:50 UTC, JackReevies commented on definitions/json/CaseEventToFields.json
> +
remove blank line

2023-07-18 09:14 UTC, JackReevies approved these changes

2023-07-18 13:42 UTC, merged