Ret 1731
hmcts/et-ccd-definitions-englandwales pull request #62
Opened 2022-04-29 13:06 UTC by robin-ieong

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-04-29 15:22 UTC, marcjudge requested changes

2022-04-29 15:22 UTC, marcjudge commented on definitions/json/AuthorisationCaseEvent.json
> +    "CaseEventID": "initiateCaseDraft",
You can remove initiateCaseDraft we're not going to use it anymore. We're INITIATE_CASE_DRAFT going forward

2022-05-03 08:46 UTC, vinothon84 approved these changes

2022-05-03 13:41 UTC, marcjudge approved these changes

2022-05-03 13:41 UTC, merged