Publishing fields for etInitialConsiderationRule27 and etInitialConsi…
hmcts/et-ccd-definitions-englandwales pull request #705
Opened 2023-11-14 12:40 UTC by addison-jephtah

…derationRule28

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-15 12:21 UTC, fergusoshea commented on definitions/json/ComplexTypes/ComplexTypes.json
> +    "Publish": "Y"
Hi @addison-jephtah 
There is no Publish on ComplexTypes. It might be needed to be added to EventToComplexTypes

2023-11-15 13:53 UTC, fergusoshea approved these changes

2023-11-15 14:01 UTC, JackReevies requested changes
Please revert ComplexTypes.json if its not being updated

2023-11-15 15:53 UTC, fergusoshea commented on definitions/json/ComplexTypes/ComplexTypes.json
> +
Blank Lines removed.

2023-11-16 13:46 UTC, brendanmchugh approved these changes

2023-11-16 13:57 UTC, marcjudge approved these changes

2023-11-16 14:00 UTC, JackReevies approved these changes

2023-11-16 14:09 UTC, merged